server:
  port: 8092
  servlet:
    context-path: /product-web

spring:
  application:
    name: product-web

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
